#include "global.h"
TextureManager g_TextureManager;
HeroInfoMG     g_HeroInfoMG;
ObjectInfoMG   g_ObjectInfoMG;
BGManager      g_BGManager;
BallptrManager g_BallptrManager;
BallptrManager g_EnemyBallptrManager;
ID3D11Device* g_d3dDevice;
int  g_Time;