#include "global.h"
TextureManager	g_TextureManager;
HeroInfoMG	g_HeroInfoMG;
HeroManager	g_HeroMG;
ObjectInfoMG	g_ObjectInfoMG;
ObjectMG	g_ObjectMG;
BGManager	g_BGManager;
ID3D11Device*	g_d3dDevice;
WavSound	g_WavePlayer;	
int  g_Time;
