//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MathFunctionCurve.cpp
//  @ Date : 2011/9/3
//  @ Author : 
//
//


#include "MathFunctionCurve.h"

Vector3 MathFunctionCurve::GetValue(float time)
{
	CheckSort();
	return m_position;
}

