//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PathInterpolater.cpp
//  @ Date : 2011/9/3
//  @ Author : 
//
//


#include "PathInterpolater.h"

void PathInterpolater::AddPoint(float time, Vector3 p)
{
	m_needsort = true;
	m_points.push_back(PathPoint(time, p));
}

void PathInterpolater::Clear()
{
	m_needsort = true;
	m_points.clear();
}

void PathInterpolater::CheckSort()
{
	if (m_needsort)
	{
		std::sort(m_points.begin(), m_points.end());
		m_needsort = false;
	}
}

