//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BezierCurve.h
//  @ Date : 2011/9/3
//  @ Author :
//
//


#if !defined(_BEZIERCURVE_H)
#define _BEZIERCURVE_H

#include "PathInterpolater.h"

class BezierCurve : public PathInterpolater
{
public:
	Vector3 GetValue( float time );
	inline Vector3 CalcBezierCurvePos( const Vector3& start, const Vector3& cnt1,
	                                   const Vector3& cnt2, const Vector3& end, float Scalar )
	{
		Vector3 out = start * ( 1.0f - Scalar ) * ( 1.0f - Scalar ) * ( 1.0f - Scalar ) +
		              cnt1 * 3.0f * Scalar * ( 1.0f - Scalar ) * ( 1.0f - Scalar ) +
		              cnt2 * 3.0f * Scalar * Scalar * ( 1.0f - Scalar ) +
		              end * Scalar * Scalar * Scalar;
		return out;
	}
};

#endif  //_BEZIERCURVE_H
